### ISSUE TITLE
[Auth] Alpha Roadmap

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#1312]
## Resources

- [Auth Spec](https://github.com/WalletConnect/walletconnect-specs/tree/main/auth)
- [Auth Client API](https://github.com/WalletConnect/walletconnect-specs/blob/main/auth/client-api.md)

## Critical Path

This is intended as an overview of critical path work to get to an alpha state with the JS Auth SDK, from which we can break out concrete and more detailed individual issues. The list may change and reorder as we see necessary during the development process.

- [ ] Set up `AuthClient` class, primary TS interfaces and types
- [ ] Pull in `@walletconnect/core`
- [ ] Set up logging
- [ ] Set up AuthEngine and `AuthEngine.init`
- [ ] Storage handling and storage key namespacing via `Core.Store`
- [ ] Specify RPC method types
- [ ] Set up Relayer events handling
- [ ] Implement `AuthClient.pair`
- [ ] Implement `AuthClient.request` and `AuthClient.respond`
- [ ] Implement associated event handlers (`on("auth_request",...)`, `on("auth_response",...)`
- [ ] Implement signature validation
- [ ] Implement getters (`AuthClient.getPendingRequests`, `AuthClient.getRequest`)
