### ISSUE TITLE
React Native Sign SDK

### ISSUE THREAD

**Issue by xzilja** [WalletConnect/walletconnect-monorepo#1338]
## Description

Uppon testing sign SDK versions beta.102, rc.0 and rc.1 in latest react-native version (fresh vanilla app), all of these came up with errors like `new TextEncoder()` being undefined. This happens in both jsc and hermes runtimes and will only get worse as react-native is moving towards preferring hermes. This issue can be solved in 2 ways i.e. heavy js polyfilling or we create @walletconnect/react-native-sign sdk that utalises Swift and Kotlin SDK's. Latter is preferred way and will result in multiple benefits for react-native users i.e. logic will run on native thread and utilize native methods for storage / networking etc. This however needs a bit of research to understand if we can successfully implement Swift and Kotlin SDKs under one nice react-native js api similar to that of js package.

## Tasks

- [ ] Create test sdk package that exposes Kotlin sdk and test against it
- [ ] If task no.1 is successful, continue with Swift sdk implementation
- [ ] If task no.1 fails, continue with js sdk polyfilling

**Comment by nomanaliakram321** [comment]
hey can you please until when you will able to solve this issue?

**Comment by nomanaliakram321** [comment]
any fix date?

**Comment by xzilja** [comment]
@nomanaliakram321 This is something I just started working on. Currently experimenting with ways to create separate react-native SDK that uses our native Swift and Kotlin SDKs under the hood. It's looking promising, but I can't give any concrete time frames yet, as this depends on other teams i.e. our iOS guys need to finish their CocoaPods milestone. Will try to have this ready this month though.

**Comment by matthewcarlreetz** [comment]
I'm currently just poly filling @nomanaliakram321 
```ts
declare global {
  function TextEncoder(): void
  function TextDecoder(): void
}

// TextEncoder/TextDecoder polyfills for utf-8 - an implementation of TextEncoder/TextDecoder APIs
// Written in 2013 by Viktor Mukhachev <vic99999@yandex.ru>
// To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
// You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.

// Some important notes about the polyfill below:
// Native TextEncoder/TextDecoder implementation is overwritten
// String.prototype.codePointAt polyfill not included, as well as String.fromCodePoint
// TextEncoder.prototype.encode returns a regular array instead of Uint8Array
// No options (fatal of the TextDecoder constructor and stream of the TextDecoder.prototype.decode method) are supported.
// TextDecoder.prototype.decode does not valid byte sequences
// This is a demonstrative implementation not intended to have the best performance

// http://encoding.spec.whatwg.org/#textencoder


function TextEncoder() {}

TextEncoder.prototype.encode = function (val: string) {
  const octets = []
  const { length } = val
  let i = 0
  while (i < length) {
    const codePoint = val.codePointAt(i)

    if (!codePoint) return 1

    let c = 0
    let bits = 0
    if (codePoint <= 0x0000007f) {
      c = 0
      bits = 0x00
    } else if (codePoint <= 0x000007ff) {
      c = 6
      bits = 0xc0
    } else if (codePoint <= 0x0000ffff) {
      c = 12
      bits = 0xe0
    } else if (codePoint <= 0x001fffff) {
      c = 18
      bits = 0xf0
    }
    octets.push(bits | (codePoint >> c))
    c -= 6
    while (c >= 0) {
      octets.push(0x80 | ((codePoint >> c) & 0x3f))
      c -= 6
    }
    i += codePoint >= 0x10000 ? 2 : 1
  }
  return octets
}

global.TextEncoder = TextEncoder

function TextDecoder() {}

TextDecoder.prototype.decode = function (octets: Uint8Array) {
  let string = ''
  let i = 0
  while (i < octets.length) {
    let octet = octets[i]
    let bytesNeeded = 0
    let codePoint = 0
    if (octet <= 0x7f) {
      bytesNeeded = 0
      codePoint = octet & 0xff
    } else if (octet <= 0xdf) {
      bytesNeeded = 1
      codePoint = octet & 0x1f
    } else if (octet <= 0xef) {
      bytesNeeded = 2
      codePoint = octet & 0x0f
    } else if (octet <= 0xf4) {
      bytesNeeded = 3
      codePoint = octet & 0x07
    }
    if (octets.length - i - bytesNeeded > 0) {
      let k = 0
      while (k < bytesNeeded) {
        octet = octets[i + k + 1]
        codePoint = (codePoint << 6) | (octet & 0x3f)
        k += 1
      }
    } else {
      codePoint = 0xfffd
      bytesNeeded = octets.length - i
    }
    string += String.fromCodePoint(codePoint)
    i += bytesNeeded + 1
  }
  return string
}

global.TextDecoder = TextDecoder

**Comment by pedrouid** [comment]
Thanks for sharing @matthewcarlreetz 🙌  Ideally we could get this fixed under `uint8arrays` package directly if not then we can maintain a fork which makes this package isomorphic for React-Native... in the meantime we will make a shim easily available to tackle this

**Comment by nomanaliakram321** [comment]
> I'm currently just poly filling @nomanaliakram321
> 
> ```ts
> declare global {
>   function TextEncoder(): void
>   function TextDecoder(): void
> }
> 
> // TextEncoder/TextDecoder polyfills for utf-8 - an implementation of TextEncoder/TextDecoder APIs
> // Written in 2013 by Viktor Mukhachev <vic99999@yandex.ru>
> // To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
> // You should have received a copy of the CC0 Public Domain Dedication along with this software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
> 
> // Some important notes about the polyfill below:
> // Native TextEncoder/TextDecoder implementation is overwritten
> // String.prototype.codePointAt polyfill not included, as well as String.fromCodePoint
> // TextEncoder.prototype.encode returns a regular array instead of Uint8Array
> // No options (fatal of the TextDecoder constructor and stream of the TextDecoder.prototype.decode method) are supported.
> // TextDecoder.prototype.decode does not valid byte sequences
> // This is a demonstrative implementation not intended to have the best performance
> 
> // http://encoding.spec.whatwg.org/#textencoder
> 
> 
> function TextEncoder() {}
> 
> TextEncoder.prototype.encode = function (val: string) {
>   const octets = []
>   const { length } = val
>   let i = 0
>   while (i < length) {
>     const codePoint = val.codePointAt(i)
> 
>     if (!codePoint) return 1
> 
>     let c = 0
>     let bits = 0
>     if (codePoint <= 0x0000007f) {
>       c = 0
>       bits = 0x00
>     } else if (codePoint <= 0x000007ff) {
>       c = 6
>       bits = 0xc0
>     } else if (codePoint <= 0x0000ffff) {
>       c = 12
>       bits = 0xe0
>     } else if (codePoint <= 0x001fffff) {
>       c = 18
>       bits = 0xf0
>     }
>     octets.push(bits | (codePoint >> c))
>     c -= 6
>     while (c >= 0) {
>       octets.push(0x80 | ((codePoint >> c) & 0x3f))
>       c -= 6
>     }
>     i += codePoint >= 0x10000 ? 2 : 1
>   }
>   return octets
> }
> 
> global.TextEncoder = TextEncoder
> 
> function TextDecoder() {}
> 
> TextDecoder.prototype.decode = function (octets: Uint8Array) {
>   let string = ''
>   let i = 0
>   while (i < octets.length) {
>     let octet = octets[i]
>     let bytesNeeded = 0
>     let codePoint = 0
>     if (octet <= 0x7f) {
>       bytesNeeded = 0
>       codePoint = octet & 0xff
>     } else if (octet <= 0xdf) {
>       bytesNeeded = 1
>       codePoint = octet & 0x1f
>     } else if (octet <= 0xef) {
>       bytesNeeded = 2
>       codePoint = octet & 0x0f
>     } else if (octet <= 0xf4) {
>       bytesNeeded = 3
>       codePoint = octet & 0x07
>     }
>     if (octets.length - i - bytesNeeded > 0) {
>       let k = 0
>       while (k < bytesNeeded) {
>         octet = octets[i + k + 1]
>         codePoint = (codePoint << 6) | (octet & 0x3f)
>         k += 1
>       }
>     } else {
>       codePoint = 0xfffd
>       bytesNeeded = octets.length - i
>     }
>     string += String.fromCodePoint(codePoint)
>     i += bytesNeeded + 1
>   }
>   return string
> }
> 
> global.TextDecoder = TextDecoder
> ```

Can you tell me where i can add this? will it be able to solve my textEncoded issue?

**Comment by xzilja** [comment]
@matthewcarlreetz @nomanaliakram321 could you try following new installation docs for `2.0.0-rc.2` (preview) https://docs.walletconnect.com/2.0/javascript/guides/react-native

It should resolve all your issues and not require any custom polyfills.

Example react-native app with new react-native implementation is also available here
https://github.com/WalletConnect/react-native-sign/tree/js-sdk/example

**Comment by matthewcarlreetz** [comment]
@IljaDaderko It appears to be working well! I will continue to test, but initially everything is looking good.

**Comment by nomanaliakram321** [comment]
> @matthewcarlreetz @nomanaliakram321 could you try following new installation docs for `2.0.0-rc.2` (preview) https://walletconnect-docs-git-react-native-docs-288aaa-walletconnect1.vercel.app/2.0/javascript/guides/react-native
> 
> It should resolve all your issues and not require any custom polyfills.
> 
> Example react-native app with new react-native implementation is also available here https://github.com/WalletConnect/react-native-sign/tree/js-sdk/example

Thanks for replying me yeah i checked it. Its look good but still it incomplete some working like Approve and reject session purposal. when you will complete remaining functionalities.

**Comment by xzilja** [comment]
@nomanaliakram321 What I mentioned above is for better experience when using js sdk inside react-native, I think you are referring to new react-native sdk. If so, that will likely take a lot of time, so I recommend you start with implementing js one first.

**Comment by alexnguyennz** [comment]
> Example react-native app with new react-native implementation is also available here
https://github.com/WalletConnect/react-native-sign/tree/js-sdk/example

Hi where is this React Native demo now? Or any existing RN examples using WC 2.0.
