### ISSUE TITLE
[Epic] v2 Provider

### ISSUE THREAD

**Issue by ganchoradkov** [WalletConnect/walletconnect-monorepo#1339]
A universal provider has to be developed supporting v2 multi-chain
Ideally, It should support the following namespaces and their respective chains

- eip155
- solana
- cosmos 

General overview of the steps needed to accomplish this task

- [x] Create `UniversalProvider` class (naming could change) that can receives config object as constructor with the relevant namespaces, relay url etc 
- [x] Add general event listeners & handlers 
- [x] Initialize `sign-client` with the provided config
- [x] Create provider classes such as`Eip155Provider` , `SolanaProvider` that are responsible are initialized if their namespace is used and are responsible for handling their respective logic and rpc requests
- [x] `Eip155Provider` - Implement `request` & `requestAsync` methods in providers that handle json rpc methods & wallet communication
- [x] `Eip155Provider` - Implement namespace validations where the provided namespace/chainId as fx parameter is used in requests with fallback to the default initialized when no parameter is provided
- [x] `Eip155Provider` - Implement `http json rpc` provider to handle requests not requiring wallet forwarding
- [x] Create types & interfaces
- [x] Create test cases for each provider
- [ ] `SolanaProvider` - Implement `request` & `requestAsync` methods in providers that handle json rpc methods & wallet communication
- [ ] `SolanaProvider` - Implement namespace validations where the provided namespace/chainId as fx parameter is used in requests with fallback to the default initialized when no parameter is provided
- [ ] `SolanaProvider` - Implement `http json rpc` provider to handle requests not requiring wallet forwarding
- [ ] `CosmosProvider` - Implement `request` & `requestAsync` methods in providers that handle json rpc methods & wallet communication
- [ ] `CosmosProvider` - Implement namespace validations where the provided namespace/chainId as fx parameter is used in requests with fallback to the default initialized when no parameter is provided
- [ ] `CosmosProvider` - Implement `http json rpc` provider to handle requests not requiring wallet forwarding
