### ISSUE TITLE
[Epic] Pairing API

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#1477]
## Resources

- Spec PR: https://github.com/WalletConnect/walletconnect-docs/pull/276
- Proposed Pairing API: https://github.com/WalletConnect/walletconnect-docs/blob/Pairing-API/docs/specs/pair/client-api.md
- PR: #1536 

## Implementation Path

This is intended as an overview of the implementation path for a shared Pairing API, which can be depended upon by Sign, Auth and future SDKs. 

Each list item should be broken out into its own issue and linked back to this epic where appropriate. The list may change and reorder as we see necessary during the development process.

- [x] Set up new `core/pairing` controller class + required typings (#1478)
- [x] Set up test suite for `core/pairing`.
- [x] Migrate pairing-related methods that currently live in SignClient into the pairing controller (e.g. `create`, `init`, `pair`, `ping`, `disconnect`). Adapt where necessary.
- [x] Implement new Pairing API methods (e.g. `getPairings`). (#1485)
- [x] Migrate validation logic for `pair`, `ping`, `disconnect`
- [x] Refactor: move `history` from `sign-client` into `core`, use `core.history` inside `sign-client` going forward (#1506)
- [x] Implement event handling, access to `pairing_ping`, `pairing_delete` events at top-level client (#1506)
- [x] Migrate pairing-specific cleanup logic to `core/pairing` controller
- [x] Refactor: move `expirer` from `sign-client` into `core`, use `core.expirer` inside `sign-client` going forward (#1525)
- [x] Implement `pairing.register`, return Error JSON-RPC response if received method type is not a `wc_pairing...` one or has not been registered. (https://github.com/WalletConnect/walletconnect-monorepo/pull/1536/commits/c8f344a6991e7f0c21ca75f2688a568741bb7bb3)
- [x] Ensure tests adhere to the proper setup/teardown logic Gancho implemented (#1518)
- [x] Extend test suite for `core/pairing` to ensure parity or better with what was covered as part of `sign-client`.

### Sign Integration (#1506)

- [x] Run SignClient with pairing logic delegated to `core/pairing`.
- [x] Ensure event handling for pairing-related events works as before
- [x] Check for any unwanted breaking changes to public interfaces of SignClient
- [x] Ensure test suite passes. Tweak test suite where necessary.
- [x] Dogfood refactored SignClient via canary release.

### Auth Integration (https://github.com/WalletConnect/auth-client-js/pull/45)

- [x] Consume `core.history` singleton instead of using own history controller
- [x] Consume `core.expirer` singleton instead of using own expirer controller
- [x] Run AuthClient with all pairing logic delegated to `core/pairing`.
- [x] Ensure event handling for pairing-related events works as before
- [x] Ensure test suite passes. Expand tests where necessary.
- [x] Dogfood refactored AuthClient via canary/alpha release.

### Documentation (https://github.com/WalletConnect/walletconnect-docs/pull/299, https://github.com/WalletConnect/walletconnect-docs/pull/304)

- [x] Document JS Pairing API
- [x] Document setup/configuration changes in Sign v2, link back to JS Pairing API where necessary
- [x] Document setup/configuration changes in Auth docs, link back to JS Pairing API where necessary
