### ISSUE TITLE
[Core] Surface concrete WebSocket errors in browser environment

### ISSUE THREAD

**Issue by bkrem** [WalletConnect/walletconnect-monorepo#2091]
## Description

* Infra has shipped an alternative error communication via the websocket's close frame via the new `?useOnCloseEvent=true` parameter (https://github.com/WalletConnect/rs-relay/pull/750)
* Since the browser's `WebSocket` implementation only returns generic/opaque events `onerror`, this allows us to surface the error/disconnection reason to the user properly, as is already possible `onerror` in node's `ws` implementation.

## Tasks

- [x] Ship required changes to support `useOnCloseEvent` in low-level deps (`@walletconnect/jsonrpc-ws-connection`, `@walletconnect/jsonrpc-provider`) - https://github.com/WalletConnect/walletconnect-utils/pull/56
- [x] Release new versions of `@walletconnect/jsonrpc-ws-connection`, `@walletconnect/jsonrpc-provider` on `latest` distro
	- [x] jsonrpc-ws-connection@1.0.10
	- [x] jsonrpc-provider@1.0.9
- [x] Integrate new WS deps versions downstream in `@walletconnect/core` - #2096 
- [x] Ship as a patch release in monorepo - https://github.com/WalletConnect/walletconnect-monorepo/releases/tag/2.4.10
