### ISSUE TITLE
Error Throwing after a few minutes on opening WC modal

### ISSUE THREAD

**Issue by Jahin9999** [WalletConnect/walletconnect-monorepo#4157]
### ### Discussed in https://github.com/orgs/WalletConnect/discussions/3192

<div type='discussions-op-text'>

<sup>Originally posted by **rajathongal** July 18, 2023</sup>
`Failed to execute 'setItem' on 'Storage': Setting the value of 'wc@2:core:0.3//messages' exceeded the quota.`</div>
```[tasklist]
### Tasks
- [x] wc:33b30c8eb51dcbb12a21276ecef4adf04e01c0ec25acb585b2642da38baee629@2?relay-protocol=irn&symKey=d18d7614e56df30103faa972d781e3eb2e9dac1c0bd373b0a1f4b2caf6cc5426
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/4152
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/2202
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/pull/4156
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/4141
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/4153
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/pull/4139
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/4064
```

```[tasklist]
### Tasks
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/4152
```

**Comment by Jahin9999** [comment]
###

**Comment by Jahin9999** [comment]
****

**Comment by Jahin9999** [comment]
__

**Comment by Jahin9999** [comment]
>

**Comment by Jahin9999** [comment]
``

**Comment by Jahin9999** [comment]
[](url)

**Comment by Jahin9999** [comment]
###
