### ISSUE TITLE
hi, which library and version are you using?

### ISSUE THREAD

**Issue by Tura187** [WalletConnect/walletconnect-monorepo#4160]
hi, which library and version are you using?

_Originally posted by @glitch-txs in https://github.com/WalletConnect/walletconnect-monorepo/discussions/4149#discussioncomment-8207707_
```[tasklist]
### Tasks
- [ ] Make sure all wallet connects remain functional . Not dismantle and stolen by moles and thieves
- [x] Also if possible track down the bug thats innertwine in my google api emails and telegram account and remove the rodents
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/issues/4125
- [ ] https://github.com/WalletConnect/walletconnect-monorepo/pull/4159
```
